function [tracks_new, new_props, index_link] = blink_correction_4(tracks, track_props, constrains)
% This function joins fragmented trajectories. This is needed as due to
% noise the signal 


partition = 20;

disp('Starting process to correct fragmented tracks due to blinking');

%% finds all possible candidates for linking based on the centroid

% In case constrains are not provided
if nargin == 2
    % Maximum distance between tracks (in pixels) for which the presence of a
    % blinker is considered
    max_distance = 1;
    % Maximum numebr of frames between the desapearence of a track and teh
    % appearence of a new one
    max_delay = 5;
    % Maximum average intensity variation between tracks as a percentage of the
    % brightest spot. Not used for now
    max_int = 0.5;
else
    max_distance = constrains(1);
    max_delay = constrains(2);
    max_int = constrains(3); % Not implemented for now
end

% gets x and y position of the average track positon for each track
x_all = [track_props(:).pos_mean_x];
y_all = [track_props(:).pos_mean_y];
xlim = ceil(max(x_all+1));
ylim = ceil(max(y_all+1));
segment_x = ceil(xlim/partition);
segment_y = ceil(ylim/partition);

% Initialises variables and extracts the one that will be used in the
% folowing loop.
link1 = [];
link2 = [];
track_num = 1:length(track_props);%[track_props(:).index];
start_frame = [track_props(:).beginning];
end_frame = [track_props(:).ending];
start_time = tic;

for ii=1:partition
    for jj=1:partition
        if ii == 1 && jj==2
            start_time = tic;
        end
        if ii == 1 && jj==5
            time_loop = toc(start_time);
            predicted_time = time_loop*partition^2/3;
            if predicted_time>10
                disp(['The extimated completion time in seconds is: ' ...
                num2str(predicted_time)]);
            end
            if predicted_time>600
                disp('Sorry, I''m a bit slow today..');
            end
        end
        lim_xlow = max((ii-1)*segment_x-2*max_distance, 1);
        lim_ylow = max((jj-1)*segment_y-2*max_distance, 1);
        lim_xhigh = min(ii*segment_x+2*max_distance, xlim);
        lim_yhigh = min(jj*segment_y+2*max_distance, ylim);
        sel_seg = x_all>lim_xlow & x_all<=lim_xhigh &...
            y_all>lim_ylow & y_all<=lim_yhigh;
        index_seg = track_num(sel_seg);
        x_part = x_all(sel_seg);
        y_part = y_all(sel_seg);
        [link1_part, link2_part] = find_links(x_part, y_part, ...
            start_frame(sel_seg), end_frame(sel_seg), max_delay, ...
            max_distance);
        link1 = [link1 index_seg(link1_part)];
        link2 = [link2 index_seg(link2_part)];
    end
end

% Since we have a small overlap between the areas there will be duplicates.
[~, link1_uni] = unique(link1);
[~, link2_uni] = unique(link2);
[~, ~, link1_extra] = setxor(link1_uni, 1:length(link1));
[~, ~, link2_extra] = setxor(link2_uni, 1:length(link2));
del_link = intersect(link1_extra, link2_extra);
link1(del_link) = [];
link2(del_link) = [];

% There might be still some double links. Two tracks connecting to the same
% or on the other hand two tracks converging to the same. For now the first
% one appearing is chosen. Refine later

[link1, index] = unique(link1);
link2 = link2(index);
[link2, index] = unique(link2);
link1 = link1(index);

%% Plot graph links

index = [track_props(:).index];%1:length(tracks);

figure
plot([track_props(:).beginning; track_props(:).ending], [index; index],'k');
hold on

time_end = [track_props(link1).ending];
time_start = [track_props(link2).beginning];

link1_index = [track_props(link1).index];
link2_index = [track_props(link2).index];

plot([time_end; time_start], [link1_index; link2_index],'r--');
xlabel('Frames');
ylabel('Track index');

drawnow

%% Combines links belonging to the same track

% Up to this point, only two tracks have been linked together. However, in
% the case of blinkers, many tracks can be generated by the same particle.
% In this section, links are analyised again to try to combine them
% further.
% In particular we are interested in links in which track2 is the same as
% track1 of a later track

% Creates a matrix will all the links
[Link1, Link2] = meshgrid(link1,link2);
% Finds which links obbey the aformentioned rule
add_links = Link1==Link2;

% initialise parameters necessary for the linking
i = 1;
clear link_cell
aux = 1:length(link1);
link_cell = [];

% Cycles through the links until link1 is empty or the loop is not escapped
while ~isempty(link1)
    % Produces a cell recording all the track produced by a single
    % particle (all the tracks that are linked together).
    % NOTE: It always takes the first two elements of link1 and link2
    % because the first element is always deleted from the vector at the
    % end of the cycle (even if no connection is created). For the same
    % reason record first element is always 1 (the initial value of temp).
    link_cell{i} = [link1(1) link2(1)];
    temp = 1;
    record = [];
    
    % Goes through all the connections and records the joined tracks in
    % link_tracks cell array.
    while true
        record = [record temp];
        % Uses the first track fulfilling the requirements.
        temp = find(add_links(aux(temp),:),1,'first');
        if isempty(temp)
            % If no more links are present, escapes the cycle
            break
        else
            link_cell{i} = [link_cell{i} link2(temp)];
        end
    end
    % Removes all the links that have been joined in this iteration (i.e.
    % the respective columns in add_links. The links will still be
    % considered in future interation, but since all the possible links
    % have been removed, nothing will be done on them.
    add_links(:,record) = [];
    link1(record) = [];
    link2(record) = [];
    aux(record) = [];
    i = i+1;
    
end

%% create new tracks
% In this last section, the tracks are connected in both "tracks" and
% "track_props" for the subsequent kinetics analysis.
% The joined tracks are concatenated at the beginning of the original
% structure arrays and the tracks used in the joining deleted.

tracks_new = [];
deleted = [];
new_props = [];

for i=1:length(link_cell)
    temp = [];
    for j=1:length(link_cell{i})
        temp_track = tracks{link_cell{i}(j)};
        if j<length(link_cell{i})
            temp_track(temp_track(:,6)>0,:) =  [];
        end
        temp = [temp; temp_track];
        deleted = [deleted link_cell{i}(j)];
    end
    tracks_new{i} = temp;
    
    % Constructs the new track_props
    % at the first iteration it copies the track properties of the first
    % element of track_props, in this way the variable has the correct
    % structure. The data are immediately deleted when calling
    % calculate_properties. Make it nicer in the future
    
    if i==1
        new_props = track_props(1);
    end
    new_props(i) = calculate_properties(temp,i);
    new_props(i).spot_index = unique(temp(:,7));
    
end

temp_index = 1:length(tracks);
temp_index(deleted) = [];
tracks_new = [tracks_new tracks(temp_index)']';
new_props = [new_props track_props(temp_index)];

for i=1:length(new_props)
    new_props(i).index = i;
end

% Creates empty vector in case no links are created
index_link = [];

for i=1:length(link_cell)
    index_link{i} = [track_props(link_cell{i}).index];
end

end

function [link1, link2] = find_links(x_all, y_all, start_frame, ...
    end_frame, max_delay, max_distance)
% Crates a matrix to be used to determine the distance between all tracks
% average positon
[x_matrix, y_matrix] = meshgrid(x_all, y_all);

distance = sqrt((x_matrix-x_matrix').^2+(y_matrix-y_matrix').^2);

% Similarly, creates a matrix to check the distance between the end of each
% track and the beginning of the next.
[matrix_start, matrix_end] = meshgrid(start_frame, end_frame);
matrix_delay = matrix_start-matrix_end;

% Marks all the allowed combination (second track starts after the first
% and within the allowed number of frames)
admitted_delay = matrix_delay>0 & matrix_delay<max_delay;

% Combined the two conditions in a final matrix. By adding
% '~admitted_delay' multipied by the maximum allowed distance to the
% distance matrixwe exclide all the track cobination that don't respect the
% time conditoin. As their distance will appear to be larger than the
% allowed one.

decision_matrix = (distance + (~admitted_delay)*max_distance)<max_distance;

% Performs the loop to find all the possible candidates.
% Goes through each line (track) and finds the first possible candidate to
% link it with (NOT THE CLOSEST).

j = 1;
link1 = [];
link2 = [];

for i=1:length(x_all)
    candidate = find(decision_matrix(i,:),1,'first'); % Maybe of the selected one run the min in the distance matrix to find the best candidate.
    if ~isempty(candidate)
        link1(j) = i;
        link2(j) = candidate;
        j = j+1;
    end
end

% Since the tracjectory cannot branch, one track can only be linked to one
% track preceding it. for this reason, only unique values of link2 are
% used.

[link2, order] = unique(link2);

% rearranges link1 accordingly.

link1 = link1(order);
end