function add_fraction_analysis(intensity_fraction, batch)

close all  % Close all open figures

% Set the default directory to open when the script is run
defaultDirectory = 'C:';

% Store the current directory
original_directory = cd;

if batch
    % In batch mode: ask user to select a folder containing .mat files
    selpath_new = uigetdir(defaultDirectory, 'Select folder');

    % Check if user canceled folder selection
    if selpath_new == 0
        warning("No folder was selected. Analysis is cancelled");
        return;
    end

    % Ensure folder path ends with '/'
    if ~strcmp(selpath_new(end), '/')
        selpath_new = strcat(selpath_new, '/');
    end

    cd(selpath_new);

    % Find all .mat files in the selected folder
    files = dir('*.mat');
    fileName_mat = {files(:).name};

    % Warn and exit if no .mat files are found
    if isempty(fileName_mat)
        warning("No file was selected. Analysis is cancelled");
        return;
    end

else
    % In single-file mode: user selects a single .mat file
    [file, selpath_new] = uigetfile('*.mat', 'Select the MAT file', defaultDirectory);

    % Ensure folder path ends with '/'
    selpath_new = strcat(selpath_new, '/');

    % Check if user canceled file selection
    if file == 0
        warning("No file was selected. Analysis is cancelled");
        return;
    end

    fileName_mat{1} = file;
end

% Change directory to the selected path
cd(selpath_new);

% Iterate over each selected .mat file
for sec_count = 1:length(fileName_mat)

    % Load current .mat file
    load(fileName_mat{sec_count});

    % Store original directory and selection path
    old_dir = original_directory;
    selpath = selpath_new;

    % Return to original directory for analysis function access
    cd(old_dir);

    % Check if the data is cumulative or single and perform the appropriate analysis
    if exist('fileNameCum', 'var')
        [fraction, parameters] = analysis_fract_intensity(parameters, intensity_fraction, cum_track, cum_spot, metadata);
    else
        [fraction, parameters] = analysis_fract_intensity(parameters, intensity_fraction, track_props, spot_record, metadata);
    end

    % Go back to selected directory for saving results
    cd(selpath);

    % Clear temporary directory variables
    clear temp_dir selpath_new

    % Save updated results into the same .mat file
    save(fileName_mat{sec_count});

    % Save all open figures generated by analysis
    FigList = findobj(allchild(0), 'flat', 'Type', 'figure');
    for iFig = 1:length(FigList)
        FigHandle = FigList(iFig);
        if isempty(FigHandle.Name)
            % Save figure as .fig and .png with unique identifiers
            savefig(FigHandle, strcat(currentfile(1:end-4), '_', num2str(iFig), '_sections.fig'));
            saveas(FigHandle, strcat(currentfile(1:end-4), '_', num2str(iFig), '_sections.png'));
        end
    end

end

% Return to the original directory at the end
cd(old_dir);