function func_reanalysis_v3_0(parameters)

% This script should be used to perform the kinetic analysis of a single
% TIRF kinetic video, or of all the video that were acquired under the same
% conditions and stored in the same folder. Only .tif file are accepted.
% The scripts detects the particles present on the surface by observing the
% prominence of the peaks generated by the particles in every frame. Then
% links the particles according to proximity in following frames to detect
% when a particle arrives and leaves the surface. Few functions are used to
% correct detection and linking errors, e.g. track fragmentation and
% duplicates, and then kinetic parameters, i.e. arrival rate and koff, are
% calculated based on the detected tracks.
% The script saves 5 images showing surface coverage, fragmented tracks
% linkage, tracks rejected due to bleaching, and the fits used for the
% determination of the arrival rate and the koff. The workspace variables
% are also saved in the same foler as the .tif file analysed.

close all

% Do you want to process all files in the selected directory?
batch_processing = parameters.batch;
% batch_processing = false;
% Do you want to divide image in several sub-areas to speed up the analysis
% This might affect the analysis.
% Insert a single number n to divide the image in nxn subimages, insert a
% vector [n, m] to divide as nxm. If no subdivision is wanted, enter 1.
parallel_areas = parameters.parallel;

% smart_param
smart_param = false;

% Double expoential analysis
double_exp = 0;

% Conversion from pixels to microns
um_conv = 0.183;


%% Parameters initialisation
%% Image analysis and particle tracking.
% Parameters that should be adjusted by the user depending on the particles
% and conditions used.

% Directory the script will open when run
defaultDirectory = 'C:\Users\k_sei\Documents\MATLAB\TIRF analysis -new version\Input';

% (real) time between consecutive frames [unit: s].
param.dt = parameters.time;

% Prominence of the peak required to see a new particle
param.prominence_high = parameters.prev_high;

% percentage of the prominence required to maintain a particle
param.prominence_low = parameters.prev_low;

% The following parameters are probably fine for multiple applications.
% however, they might need a tweek in special occasions.

% Starting frame
param.istart = parameters.start;

% End frame, if NaN all file;
param.iend = parameters.end;

% Min track length
param.minTrackLength = parameters.length;

% Maximum distance allowed for linking particles in two successive frames
% in pixels
param.maxJumpDistance = parameters.jump;

% Minimum area of a detected spot (in pixels)
param.minSpotSize = parameters.spotSize;

% Number of frames recorded after detachment
param.buffer = parameters.buffer;

%% Blinking correction

% Maximum alloed distance between the centroids of the tracks
param.maxDistanceLink = parameters.linkDist;

% Maximum time inteval allowed between the end of the first trace and the
% start of the second one
param.maxDelay = parameters.linkDelay;%round(150)/param.dt;

% Currently NOT in use. Compares the intensity of the two traces to
% undestand is they are created by the same particle
param.intensityLink = 0.5;

%% Bleaching correction

param.minStep = parameters.bleachStep;

%% Selects files to analyse
% Let the user select the .tiff file to analyse, or, in case
% batch_precessing is activated, the folder containing all the files to
% analyse

old_dir = cd;

if batch_processing
    
    % Display a dialog box from where to the image-file to be analyzed is chosen.
    % Default directory is User-dependent.
    
    selpath = parameters.path;
    if selpath == 0
        warning("No folder was selected. Analisis is cancelled");
        return
    end
    if ~strcmp(selpath(end),'/')
        selpath = strcat(selpath, '/');
    end
    cd(selpath);
    
    files = dir('*SpotSize*.mat');
    fileName = {files(:).name};
    
    if isempty(fileName)
        warning("No file was selected. Analisis is cancelled");
        return
    end
    
else
    path = parameters.path;
    [selpath, file, fExt] = fileparts(path);
    selpath = strcat(selpath, '/');
    file = strcat(file, fExt);
    if file == 0
       warning("No file was selected. Analisis is cancelled");
       return
    end
    fileName{1} = file;
end

cd(old_dir);

for i=1:length(fileName)
    
    close all
    clear spot_record metadata tracks track_props duration cum_duration...
       arrival cum_arrival particle_frame frame_props surf_coverage
    
    currentfile = fileName{i};
    
    cd(selpath)
    
    % Image analysis
    load(currentfile, 'spot_record', 'metadata', 'matFileName');
    
%     [spot_record, metadata, matFileName] = ...
%        tirf_analyzer_3v0(param, currentfile, selpath, parallel_areas);
    cd(old_dir);
    
    % Retrives the size of the image to normalise attachment
    temp = strfind(currentfile, '-');
    currentfile = currentfile(1:temp(end-1)-2);
    name_tiff = strcat(currentfile,'.tif');
    
    [~, ~, ~, param] = get_size_image(param, strcat(name_tiff), selpath, um_conv);
    
    % metadata.deltaT = param.dt;
    [tracks, track_props] = separate_tracks(spot_record);
    
    % Remove too short tracks
    [tracks, track_props] = filter_duration(tracks, track_props, param.minTrackLength);
    
    % Calculates surface coverage
    [particle_frame, frame_props, surf_coverage, surf_cov_slope] = surface_coverage_stuck(track_props, metadata);
    
    % Blinking correction
    [tracks, track_props, links] = blink_correction_4(tracks, track_props, ...
        [param.maxDistanceLink param.maxDelay param.intensityLink]);
    
    % tracks doubling correction
    [tracks, track_props] = remove_duplicates_2(tracks, track_props, param.maxDistanceLink*2);
    
    % Bleaching correction
    [tracks, track_props, bleach_tracks, bleach_props, step_size] = ...
        bleach_correction_step(tracks, track_props, param);
    
    % Analyze remaining tracks
    [duration,cum_duration,arrival,cum_arrival,gof_analysis,...
        fit_dissociation,fit_association] = track_analysis(track_props, metadata, param.pictureArea);
    
    % Analysis dissociaiton with double exponential as well
    if double_exp == 1
        [fit_dissociation_2exp, gof_2edx] = doubleExpFit(cum_duration, duration, metadata, fit_dissociation);
    end
    
    cd(selpath);
    
    % Get a list of all variables
    allvars = whos;
    
    % Identify the variables that ARE NOT graphics handles. This uses a regular
    % expression on the class of each variable to check if it's a graphics object
    tosave = cellfun(@isempty, regexp({allvars.class}, '^matlab\.(ui|graphics)\.'));
    
    % Pass these variable names to save
    save(strcat(matFileName, '.mat'), allvars(tosave).name)
    
    %save(strcat(matFileName, '.mat'));
    
    FigList = findobj(allchild(0), 'flat', 'Type', 'figure');
    for iFig = 1:length(FigList)
        FigHandle = FigList(iFig);
        if isempty(FigHandle.Name)
            %FigName = get(FigHandle, 'Name');
            savefig(FigHandle, strcat(currentfile, '_', num2str(iFig), '.fig'));
            saveas(FigHandle, strcat(currentfile, '_', num2str(iFig), '.png'));
        end
    end
    
    cd(old_dir)
end