% This script should be used to perform the kinetic analysis of a single
% TIRF kinetic video, or of all the video that were acquired under the same
% conditions and stored in the same folder. Only .tif file are accepted.
% The scripts detects the particles present on the surface by observing the
% prominence of the peaks generated by the particles in every frame. Then
% links the particles according to proximity in following frames to detect
% when a particle arrives and leaves the surface. Few functions are used to
% correct detection and linking errors, e.g. track fragmentation and
% duplicates, and then kinetic parameters, i.e. arrival rate and koff, are
% calculated based on the detected tracks.
% The script saves 5 images showing surface coverage, fragmented tracks
% linkage, tracks rejected due to bleaching, and the fits used for the
% determination of the arrival rate and the koff. The workspace variables
% are also saved in the same foler as the .tif file analysed.

clear
close all

% Do you want to process all files in the selected directory?
parameters.batch = true;
% batch_processing = false;
% Do you want to divide image in several sub-areas to speed up the analysis
% This might affect the analysis.
% Insert a single number n to divide the image in nxn subimages, insert a
% vector [n, m] to divide as nxm. If no subdivision is wanted, enter 1.
parameters.parallel = 4;

% smart_param
smart_param = false;

% % divide analysis by intensity
% parameters.intensityFraction = [100 200 1000];

%% Parameters initialisation
%% Image analysis and particle tracking.
% Parameters that should be adjusted by the user depending on the particles
% and conditions used.

% Directory the script will open when run
defaultDirectory = 'G:\Data\Datadrive D\Fouzia\2023\20230622_Apoe\TIFs for analysis\NewAnalysis';

% (real) time between consecutive frames [unit: s].
parameters.time = 1;

% Prominence of the peak required to see a new particle
parameters.prev_high = 30;

% percentage of the prominence required to maintain a particle
parameters.prev_low = 0.4;

% The following parameters are probably fine for multiple applications.
% however, they might need a tweek in special occasions.

% Starting frame
parameters.start = 1;

% End frame, if NaN all file;
parameters.end = nan;

% Min track length
parameters.length = 3;

% Maximum distance allowed for linking particles in two successive frames
% in pixels
parameters.jump = 10;

% Minimum area of a detected spot (in pixels)
parameters.spotSize = 3;

% Number of frames recorded after detachment
parameters.buffer = 10;

%% Blinking correction

% Maximum alloed distance between the centroids of the tracks
parameters.linkDist = 2;

% Maximum time inteval allowed between the end of the first trace and the
% start of the second one
parameters.linkDelay = 5;%round(150)/param.dt;

% Currently NOT in use. Compares the intensity of the two traces to
% undestand is they are created by the same particle
parameters.linkIntensity = 0.5;

%% Bleaching correction

parameters.bleachStep = NaN;

%% Selects files to analyse
% Let the user select the .tiff file to analyse, or, in case
% batch_precessing is activated, the folder containing all the files to
% analyse

old_dir = cd;

if parameters.batch
    
    % Display a dialog box from where to the image-file to be analyzed is chosen.
    % Default directory is User-dependent.
    
    parameters.path = uigetdir(defaultDirectory, 'Select folder');
    
else
    [file,selpath] = uigetfile( ...
    {'*.tif;*.tiff;*.nd2', 'Image files (*.tif, *.tiff, *.nd2)'; ...
     '*.tif;*.tiff',      'TIFF files (*.tif, *.tiff)'; ...
     '*.nd2',             'ND2 files (*.nd2)'}, ...
    'Select image file', defaultDirectory);
    parameters.path = strcat(selpath,file);
end

cd(old_dir);

func_main_v3_1(parameters)